# CLHLS-diet paper time dependent analysis

require(haven)
require(survminer)
require(survival)
require(dplyr)

setwd("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/data")
data <- read_dta("diet_timedepen.dta") # data is generated by Diet_timedependent_code2018.do by Yaxi

# -------------------------------------------- recode saltveg, sugar------------------------------------------- #
data$saltveg2 <- NA
for(i in 1:nrow(data)) {
  if(isTRUE(data$saltveg[i] == 3)) {
    data$saltveg2[i] <- 0
  } else if(isTRUE(data$saltveg[i] == 2)) {
    data$saltveg2[i] <- 1
  } else if(isTRUE(data$saltveg[i] == 1)) {
    data$saltveg2[i] <- 2
  }
}

data$sugar2 <- NA
for(i in 1:nrow(data)) {
  if(isTRUE(data$sugar[i] == 3)) {
    data$sugar2[i] <- 0
  } else if(isTRUE(data$sugar[i] == 2)) {
    data$sugar2[i] <- 1
  } else if(isTRUE(data$sugar[i] == 1)) {
    data$sugar2[i] <- 2
  }
}

# ------------------------------------------ Table 2: single variate ------------------------------------------ #
food <- c("fruit1", "veg1", "meat1", "fish1", "egg1", "bean1", "saltveg2", "sugar2", "tea1", "garlic1")

data[, food] <- apply(data[, food], 2, as.factor)

data_male <- filter(data, gender == 1)
data_female <- filter(data, gender == 0)

cox_single <- list()
cox_single_male <- list()
cox_single_female <- list()

for(f in food) {
  cox_single[[f]] <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ data[[f]] + baseage + 
                             gender, data =  data))
  write.csv(cbind(cox_single[[f]]$coefficients, cox_single[[f]]$conf.int), 
            file = paste("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 2_total/", f, ".csv", sep = ""))
  
  cox_single_male[[f]] <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ data_male[[f]] +
                                  baseage, data =  data_male))
  write.csv(cbind(cox_single_male[[f]]$coefficients, cox_single_male[[f]]$conf.int), 
            file = paste("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 2_male/", f, "_male.csv", sep = ""))
  
  cox_single_female[[f]] <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ data_female[[f]] +
                                    baseage, data =  data_female))
  write.csv(cbind(cox_single_female[[f]]$coefficients, cox_single_female[[f]]$conf.int), 
            file = paste("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 2_female/", f, "_female.csv", sep = ""))
}

# ------------------------------------------- Table 3: multivariate ------------------------------------------- #
var <- c("SHE8", "edug", "coresidence", "smkl", "dril")
data[, var] <- apply(data[, var], 2, as.factor)
data_male[, var] <- apply(data_male[, var], 2, as.factor)
data_female[, var] <- apply(data_female[, var], 2, as.factor)

data$ethnicity <- factor(data$ethnicity, levels = c("1", "0"))
data$occupation <- factor(data$occupation, levels = c("1", "0"))
data_male$ethnicity <- factor(data_male$ethnicity, levels = c("1", "0"))
data_male$occupation <- factor(data_male$occupation, levels = c("1", "0"))
data_female$ethnicity <- factor(data_female$ethnicity, levels = c("1", "0"))
data_female$occupation <- factor(data_female$occupation, levels = c("1", "0"))

# multivariate model in total
cox_multi <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8 + baseage + 
                             edug + ethnicity + marital + residence + occupation + coresidence + smkl + pa + dril + strata(gender), data =  data))
write.csv(cbind(cox_multi$coefficients, cox_multi$conf.int),
          file = "F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 3/cox_multi_total.csv")

# multivariate model in male
cox_multi_male <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8 + baseage + 
                             edug + ethnicity + marital + residence + occupation + coresidence + smkl + pa + dril, data =  data_male))
write.csv(cbind(cox_multi_male$coefficients, cox_multi_male$conf.int),
          file = "F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 3/cox_multi_male.csv")

# multivariate model in female
cox_multi_female <- summary(coxph(formula = Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8 + baseage + 
                                  edug + ethnicity + marital + residence + occupation + coresidence + smkl + pa + dril, data =  data_female))
write.csv(cbind(cox_multi_female$coefficients, cox_multi_female$conf.int),
          file = "F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/table 3/cox_multi_female.csv")

# ----------------------------------------------- survival curve ---------------------------------------------- #
# time_dependent_total
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/time_dependent_survival_curve_total.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8, data = data), 
           data = data, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Time dependent total")
dev.off()

# time_dependent_male
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/time_dependent_survival_curve_male.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8, data = data_male), 
           data = data_male, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Time dependent male")
dev.off()

# time_dependent_female
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/time_dependent_survival_curve_female.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = sur_year, time2 = sur_year_forward, event = status) ~ SHE8, data = data_female), 
           data = data_female, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Time dependent female")
dev.off()

# not_time_dependent_total
data2 <- read_dta("diet9_baseline2018.dta")
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/not_time_dependent_survival_curve_total.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = survtime, event = death) ~ SHE8, data = data2), 
           data = data2, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Not time dependent total")
dev.off()

# not_time_dependent_male
data2_male <- filter(data2, gender == 1)
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/not_time_dependent_survival_curve_male.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = survtime, event = death) ~ SHE8, data = data2_male), 
           data = data2_male, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Not time dependent male")
dev.off()

# not_time_dependent_female
data2_female <- filter(data2, gender == 0)
pdf("F:/Box Sync/Duke Kunshan University Intern/4 Diet/P02 Diet-Mort-NEJM/timedependent_ZH/output/survival curve/not_time_dependent_survival_curve_female.pdf", 
    width = 7.23, height = 7.23)
ggsurvplot(survfit(Surv(time = survtime, event = death) ~ SHE8, data = data2_female), 
           data = data2_female, 
           risk.table = TRUE,
           fontsize = 3,
           xlab = "Follow up time(d)",
           legend.title = "",
           legend.labs = c("Q1", "Q2", "Q3", "Q4"), 
           break.x.by = 4,
           title = "Not time dependent female")
dev.off()